### ISSUE TITLE
[Screen] Параметры печати на экране Print_Setup

### ISSUE THREAD

**Issue by Sencudra** [Sencudra/3d_printer#6]
Какие из параметров из #1 должны настраиваться с помощью экрана?
Какие еще могу быть параметры?

На данный момент:
- Выбор пресета температуры PLA, ABS, PVA + 3 кастомных. В пресете идет температура стола, экструдера и мощность куллера.
- Высота слоя (Layer Width)
- Shall width (Не помню для чего это)

**Comment by andrey99429** [comment]
Shall width - это 
```cpp
float shell_thickness = 1.0f; //!< Толщена стенок (мм). Не будет реализовано в данной версии.
```

Думаю, что нужно оставить. Возможно, потом доделаю.

**Comment by Sencudra** [comment]
Не думаю, что это к толщине относилось, на тот момент я и не мог знать о толщине стенок. Скорее всего это для ```nozzle_diameter```.  ```nozzle_diameter``` вообще может меняться?

**Comment by andrey99429** [comment]
Нет, он не может меняться.
